- name: Wordpress_deploy
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    - name: Update OS Ubuntu Server 20.04
      command: apt -y update    
         
    - name: Install required system packages for Docker CE
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'python3-setuptools', 'virtualenv']
    
    - name: Install Docker py
      command: pip3 install docker-py
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    
    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: dc_wordpress.yml
        dest: /ansible/
        owner: ubuntu
        group: root
        mode: u=rw,g=r,o=r

    - name: Start Docker-compose
      command: 'docker-compose up -d' 